# Publish the latest vaccination data for a country
name: Tweet daily sum up

on:
  schedule:
    # Hourly run the workflow to check for updates
    - cron: "45 19 * * *"
  # Manually run the workflow for debugging
  workflow_dispatch:

jobs:
  publish:
    name: Publish tweet
    runs-on: ubuntu-latest
    steps:

      - name: Checkout covid_vaccine_progress_bot
        uses: actions/checkout@v2
        with:
          path: covid_vaccine_progress_bot

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install requirements
        run: pip install -r ${{ github.workspace }}/covid_vaccine_progress_bot/requirements.txt

      - name: Tweet EU data
        env:
          DATA: ${{ github.workspace }}/covid-19-data/scripts/
          INPUT: ${{ github.workspace }}/covid-19-data/scripts/output/vaccinations/
          OUTPUT: ${{ github.workspace }}/covid_vaccine_progress_bot/output
          POPULATION: ${{ github.workspace }}/covid_vaccine_progress_bot/population_2020.csv
          BOT_API: ${{ secrets.BOT_API }}
          BOT_API_SECRET: ${{ secrets.BOT_API_SECRET }}
          BOT_ACCESS: ${{ secrets.BOT_ACCESS }}
          BOT_ACCESS_SECRET: ${{ secrets.BOT_ACCESS_SECRET }}
          TELEGRAM: ${{ secrets.TELEGRAM_API }}
        run: python ${{ github.workspace }}/covid_vaccine_progress_bot/.github/utils/publish_eu.py

      - name: Publish tweet
        env:
          DATA: ${{ github.workspace }}/covid_vaccine_progress_bot/output/
          POPULATION: ${{ github.workspace }}/covid_vaccine_progress_bot/population_2020.csv
          OUTPUT: ${{ github.workspace }}/covid_vaccine_progress_bot/output/
          FLAGS: ${{ github.workspace }}/covid_vaccine_progress_bot/flags/
          BOT_API: ${{ secrets.BOT_API }}
          BOT_API_SECRET: ${{ secrets.BOT_API_SECRET }}
          BOT_ACCESS: ${{ secrets.BOT_ACCESS }}
          BOT_ACCESS_SECRET: ${{ secrets.BOT_ACCESS_SECRET }}
        run: python ${{ github.workspace }}/covid_vaccine_progress_bot/.github/utils/graphs.py

