# Publish the latest vaccination data for a country
name: Tweet latest vaccination data

on:
  schedule:
    # Hourly run the workflow to check for updates
    - cron: "* 22 * * *"
  # Manually run the workflow for debugging
  workflow_dispatch:

jobs:
  publish:
    name: Publish tweet
    runs-on: ubuntu-latest
    steps:

      - name: Checkout covid_vaccine_progress_bot
        uses: actions/checkout@v2
        with:
          path: covid_vaccine_progress_bot

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install requirements
        run: pip install -r ${{ github.workspace }}/covid_vaccine_progress_bot/requirements.txt

      - name: Create JSON
        env:
          GREECE_SECRET: ${{ secrets.GREECE_TOKEN}}
        run: echo -e "{\"greece_api_token\":\"$GREECE_SECRET\"}" > ${{ github.workspace }}/covid-19-data/scripts/scripts/vaccinations/vax_dataset_config.json

      - name: Publish tweet
        env:
          DATA: ${{ github.workspace }}/covid_vaccine_progress_bot/output
          POPULATION: ${{ github.workspace }}/covid-19-data/scripts/input/un/population_2020.csv
          BOT_API: ${{ secrets.BOT_API }}
          BOT_API_SECRET: ${{ secrets.BOT_API_SECRET }}
          BOT_ACCESS: ${{ secrets.BOT_ACCESS }}
          BOT_ACCESS_SECRET: ${{ secrets.BOT_ACCESS_SECRET }}
        run: bash ${{ github.workspace }}/covid_vaccine_progress_bot/.github/utils/graphs.py

